### ISSUE TITLE
Issue 7: Styling-Feinschliff und Responsivität

### ISSUE THREAD

**Issue by bzharkrk** [bzharkrk/visitenkarte#7]
**Ziel:** Stelle sicher, dass die Visitenkarte auf allen Geräten gut aussieht und funktioniert.

**Beschreibung:**
Passe das Styling an, damit die Karte auf Desktops, Tablets und Handys gut aussieht (Responsive Design).

**Schritte:**

1.  **Testen:** Nutze Browser Developer Tools (F12) -> Responsive Design Mode.
2.  **Media Queries:** Füge `@media`-Regeln in dein CSS (z.B. `BusinessCard.module.css`) ein.
    ```css
    /* Beispiel für kleinere Bildschirme */
    @media (max-width: 768px) { /* Tablet */
      .card { width: 90%; max-width: 400px; /*...*/ }
    }
    @media (max-width: 480px) { /* Handy */
      .card { height: auto; min-height: 250px; padding: 15px; /*...*/ }
      .skills, .intro { font-size: 0.9em; /*...*/ }
      .contactForm input, .contactForm textarea { width: 100%; /*...*/ }
    }
    ```
    Passe Breiten, Schriftgrößen, Abstände nach Bedarf an.
3.  **Feinschliff:** Überprüfe alles: Abstände, Farben, Lesbarkeit, Animation auf Touch (falls Klick-Trigger).

**Akzeptanzkriterien (AC):**
* [ ] Karte wird auf Desktop, Tablet, Mobile korrekt dargestellt.
* [ ] Texte sind auf allen Größen lesbar.
* [ ] Formular ist auf kleinen Screens bedienbar.
* [ ] Drehanimation funktioniert auf allen Größen / Touch (falls Klick).
* [ ] Gesamtdesign ist stimmig und minimalistisch.
